"""
Django settings for amsol project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', "dhikCcOvJdxUVz0BPndtjpxYIC2vU8YJn8J4fGBYfqI=")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gf2snf)7+dk_9zikyi2v*#v!4obvr-#soiyl6g!!41zdys1u(i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "unsurrendered-duskily-linnie.ngrok-free.dev"]


CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173'
]
CORS_ALLOW_CREDENTIALS = True

# Application definition
INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party 
    'rest_framework',
    #'django_cryptography',
    'rest_framework_simplejwt', 
    'django_celery_results',
    'django_celery_beat',
    'django_filters',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'corsheaders',

    # Your apps
    'accounts.apps.AccountsConfig',  
    'clients.apps.ClientsConfig',   
    'core.apps.CoreConfig',
    'alerts.apps.AlertsConfig',
    'customers.apps.CustomersConfig',
    'meters.apps.MetersConfig',
    'payments.apps.PaymentsConfig',
    'tokens.apps.TokensConfig',
    'integrations.apps.IntegrationsConfig',
    
]

# Custom user model (matches accounts/models.py class User)
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amsol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amsol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'amsolwatervend', # .get from env in pro
        'USER': 'venduser',
        'PASSWORD': 'venduser',
        'HOST': '127.0.0.1', # Use 'localhost' or your DB host
        'PORT': '5432',
        'CONN_MAX_AGE': 60,  # Persistent connections
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # optional but recommended
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'AMSOL Water Vending API',
    'VERSION': '1.0.0',
    # optional: lock down docs to authenticated users only
    # 'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAuthenticated'],
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STRONPOWER_BASE_URL = 'http://www.server-newv.stronpower.com'
STRONPOWER_DIRECT_BASE_URL = 'http://www.server-api.stronpower.com'