# Generated by Django 5.2.7 on 2025-10-16 11:31

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_info', models.TextField(blank=True)),
                ('paybill_number', models.CharField(max_length=20, unique=True)),
                ('stronpower_company_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('stronpower_username', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('stronpower_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('billing_info', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['paybill_number'], name='clients_paybill_69b0f6_idx'), models.Index(fields=['is_active'], name='clients_is_acti_43299d_idx')],
            },
        ),
    ]
