# Generated by Django 5.2.7 on 2025-10-16 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('customers', '0001_initial'),
        ('meters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_token', 'Low Token Warning'), ('tamper', 'Tamper Alert'), ('fault', 'Meter Fault'), ('offline', 'Meter Offline'), ('payment_failed', 'Payment Failed'), ('vending_failed', 'Vending Failed')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('sent_to', models.JSONField(default=list)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='clients.client')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='customers.customer')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='meters.meter')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'is_acknowledged'], name='alerts_client__753198_idx'), models.Index(fields=['alert_type', 'severity'], name='alerts_alert_t_cb4af9_idx'), models.Index(fields=['created_at'], name='alerts_created_965da5_idx')],
            },
        ),
    ]
