# Generated by Django 5.2.7 on 2025-10-16 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('meter_type', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('tamper', 'Tamper'), ('fault', 'Fault'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_tamper_event', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='clients.client')),
            ],
            options={
                'db_table': 'meters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_on', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_assignments', to='customers.customer')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='meters.meter')),
            ],
            options={
                'db_table': 'meter_assignments',
                'ordering': ['-assigned_on'],
            },
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['client', 'status'], name='meters_client__3d5998_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['meter_id'], name='meters_meter_i_f83a96_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['status'], name='meters_status_3e5e26_idx'),
        ),
        migrations.AddIndex(
            model_name='meterassignment',
            index=models.Index(fields=['meter', 'is_active'], name='meter_assig_meter_i_cc6a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='meterassignment',
            index=models.Index(fields=['customer', 'is_active'], name='meter_assig_custome_ce72b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meterassignment',
            unique_together={('meter', 'customer', 'is_active')},
        ),
    ]
