# Generated by Django 5.2.7 on 2025-10-16 11:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('meters', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_value', models.CharField(max_length=255)),
                ('token_type', models.CharField(choices=[('vending', 'Vending Token'), ('clear_credit', 'Clear Credit Token'), ('clear_tamper', 'Clear Tamper Token')], default='vending', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('units', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_vend_by_unit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='customers.customer')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tokens', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='meters.meter')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='payments.paymentnotification')),
            ],
            options={
                'db_table': 'tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vending_requests', to='payments.paymentnotification')),
                ('token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vending_request', to='tokens.token')),
            ],
            options={
                'db_table': 'vending_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['meter', 'status'], name='tokens_meter_i_6da46e_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['customer', 'created_at'], name='tokens_custome_975585_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['status'], name='tokens_status_0bafa4_idx'),
        ),
        migrations.AddIndex(
            model_name='vendingrequest',
            index=models.Index(fields=['status', 'next_retry_at'], name='vending_req_status_3d7174_idx'),
        ),
        migrations.AddIndex(
            model_name='vendingrequest',
            index=models.Index(fields=['idempotency_key'], name='vending_req_idempot_4ab768_idx'),
        ),
        migrations.AddIndex(
            model_name='vendingrequest',
            index=models.Index(fields=['payment'], name='vending_req_payment_716b02_idx'),
        ),
    ]
